project:
  type: website

website:
  title: "Nowell Phelps Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

bibliography: refs.bib
